# Generated by Django 5.0.4 on 2024-05-16 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp", "0002_topic_room_host_message_room_topic_created"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Topic",
            new_name="StackTopic",
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.RenameField(
            model_name="room",
            old_name="topic_created",
            new_name="stack",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="name",
            new_name="topic_name",
        ),
        migrations.RenameField(
            model_name="stacktopic",
            old_name="topic_name",
            new_name="stacks_name",
        ),
    ]
