# Generated by Django 5.0.4 on 2024-06-27 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp", "0003_rename_topic_stacktopic_alter_room_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="room_sending_msg",
            new_name="room_receiving_msg",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="user",
            new_name="user_sending_msg",
        ),
    ]
