# Generated by Django 5.0.4 on 2024-06-27 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp", "0004_rename_room_sending_msg_message_room_receiving_msg_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="participant",
            field=models.ManyToManyField(
                blank=True, related_name="participant", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
